### PR TITLE
Update page titles and metatag descriptions

### PR DESCRIPTION
**Pull request by darkbrewery**
The Trad/Simple translations already say "Welcome to otter kingdom" this just catches the English version up

### CODE REVIEW

**Comment by darkbrewery** [comment]
image

**Comment by darkbrewery** [comment]
Before: image

After: image

**Comment by pyc92** [comment]
@darkbrewery All looks good. Could you please fix the conflicts, then I will merge the PR?

**Comment by darkbrewery** [comment]
> @darkbrewery All looks good. Could you please fix the conflicts, then I will merge the PR?

On It!

**Comment by darkbrewery** [comment]
Looks like I messed that up, gimme a few will reslove properly

**Comment by darkbrewery** [comment]
@pyc92 Here you go, resolved

**Pull request merged**
